# Paths
PDK 			?= sky130A
FABRIC 			?= classic_fabric_chipfoundry_large
TILE_LIBRARY		?= classic
FABULOUS_ROOT 		?= $(abspath ../../../../fabrics/$(FABRIC)/macro/$(PDK)/fabulous)
#PCF_CONSTRAINTS 		?= $(abspath $(FABULOUS_ROOT)/../../../constraints.pcf)
PCF_CONSTRAINTS 		 = $(abspath ./generated_constraints.pcf)
FABRIC_CSV              ?= $(abspath ../../../../fabrics/$(FABRIC)/$(FABRIC).csv)
PCF_GEN_SCRIPT          ?= $(abspath ../../../scripts/generate_pcf.py)
TOP 			?= top_wrapper

# Available flip-flops and init value
# NOTE: -ff option syntax appears problematic in current yosys version.
# Leaving empty - synth_fabulous works without explicit FF specification.
FFS                     ?= -ff \$$_DFF_P_ x \
			   -ff \$$_DFFE_PP_ x \
			   -ff \$$_SDFF_PP?_ x \
			   -ff \$$_SDFFE_PP?P_ x \
			   -ff \$$_DLATCH_?_ x

$(info $(PDK))
$(info $(FABRIC))
$(info $(TILE_LIBRARY))

ifeq ($(TILE_LIBRARY),classic)
# MULTIPLIER_MAP_PATH 	 = -multiplier-map ../../../../ip/fabulous-tiles/primitives/MACC_8x8_20/yosys/techmap/MACC_8x8_20_map.v
endif

EXTRA_PLIBS_PATH 	 = -extra-plib ../../../../ip/fabulous-tiles/primitives/FABULOUS_LC/yosys/primitives/prims.v \
			   -extra-plib ../../../../ip/fabulous-tiles/primitives/IOBUF/yosys/primitives/IOBUF.v \
			   -extra-plib ../../../../ip/fabulous-tiles/primitives/IBUF/yosys/primitives/IBUF.v \
			   -extra-plib ../../../../ip/fabulous-tiles/primitives/OBUF/yosys/primitives/OBUF.v \
			   -extra-plib ../../../../ip/fabulous-tiles/primitives/TBUF/yosys/primitives/TBUF.v \
			   -extra-plib ../../../../ip/fabulous-tiles/primitives/GBUF/yosys/primitives/GBUF.v \
   			   -extra-plib ../../../../ip/fabulous-tiles/primitives/SYS_RESET/yosys/primitives/SYS_RESET.v

ifeq ($(TILE_LIBRARY),classic)
EXTRA_PLIBS_PATH 	+= -extra-plib ../../../../ip/fabulous-tiles/primitives/RAM_32x4_2R_1W/yosys/primitives/RAM_32x4_2R_1W.v \
   			   -extra-plib ../../../../ip/fabulous-tiles/primitives/MACC_8x8_20/yosys/primitives/MACC_8x8_20.v
endif


EXTRA_MAPS_PATH		 = -extra-map ../../../../ip/fabulous-tiles/primitives/FABULOUS_LC/yosys/techmap/lut_map.v \
			   -extra-map ../../../../ip/fabulous-tiles/primitives/FABULOUS_LC/yosys/techmap/ff_map.v \
			   -extra-map ../../../../ip/fabulous-tiles/primitives/IOBUF/yosys/techmap/IOBUF_map.v

ifeq ($(TILE_LIBRARY),classic)
EXTRA_MAPS_PATH		+= -extra-map ../../../../ip/fabulous-tiles/primitives/RAM_32x4_2R_1W/yosys/techmap/RAM_32x4_2R_1W_map.v
endif

ifeq ($(TILE_LIBRARY),classic)
#EXTRA_MLIBMAPS_PATH	 = -extra-mlibmap ../../../../ip/fabulous-tiles/primitives/RAM_32x4_2R_1W/yosys/memlib/RAM_32x4_2R_1W_lib.txt
endif


BIT_GEN 			?= ../../../scripts/bit_gen.py
BIT_TO_HEX 		?= ../../../scripts/bit_to_hex.py

all: synth generate-pcf pnr bitstream hex

generate-pcf: $(PCF_CONSTRAINTS)

$(PCF_CONSTRAINTS): $(FABRIC_CSV) $(TOP).json
	@python3 $(PCF_GEN_SCRIPT) $(FABRIC_CSV) $(TOP).json $(PCF_CONSTRAINTS)
	@echo "Generated $(PCF_CONSTRAINTS)"


synth:
	yosys \
	-p \
	"synth_fabulous \
	-top $(TOP) \
	-lut 4 \
	-carry ha \
	-complex-dff \
	$(FFS) \
	$(EXTRA_PLIBS_PATH) \
	$(EXTRA_MAPS_PATH); \
	show -format dot -prefix $(TOP); \
	write_json -noscopeinfo $(TOP).json; \
	" \
	$(RTL)
.PHONY: synth

pnr: $(PCF_CONSTRAINTS) $(TOP).json
	FAB_ROOT=$(FABULOUS_ROOT) \
	nextpnr-generic \
	--uarch fabulous \
	--json $(TOP).json \
	--write $(TOP)_out.json \
	-o fasm=$(TOP).fasm \
	-o pcf=$(PCF_CONSTRAINTS) \
	--verbose \
	--log $(TOP)_log.txt \
	--timing-allow-fail
.PHONY: pnr

bitstream:
	python3 $(BIT_GEN) \
	-genBitstream \
	$(TOP).fasm \
	$(FABULOUS_ROOT)/bitStreamSpec.bin \
	$(TOP).bit
.PHONY: bitstream

hex:
	python3 $(BIT_TO_HEX) \
	$(TOP).bit \
	$(TOP).hex

clean:
	rm -rf $(TOP).json
	rm -rf $(TOP)_out.json
	rm -rf $(TOP).fasm
	rm -rf $(TOP)_log.txt
	rm -rf $(TOP).bit
	rm -rf $(TOP).hex
	rm -rf $(TOP).vh
	rm -rf $(TOP).vhd
	rm -rf $(TOP).csv
	rm -rf $(TOP).dot
.PHONY: clean

help:
	@echo "Commands:"
	@echo " synth           ... Synthesize the user design"
	@echo " pnr             ... Run Place and Route"
	@echo " bitstream       ... Generate the bitstream"
	@echo " hex             ... Convert bitstream to hex"
	@echo " clean           ... Delete all generated files"
	@echo " help            ... Show this help message"
.phony: help
