meta:
  version: 3
  flow: Chip
  substituting_steps:

    # Magic reports some overlaps which can be ignored
    Checker.IllegalOverlap: null

    # Disable KLayout DRC
    #KLayout.DRC: null
    #Checker.KLayoutDRC: null

    # Disable magic DRC
    Magic.DRC: null
    Checker.MagicDRC: null

    # Disable KLayout antenna check
    #KLayout.Antenna: null
    #Checker.KLayoutAntenna: null

    # Disable KLayout density check
    #KLayout.Density: null
    #Checker.KLayoutDensity: null
    
    # Save time
    #OpenROAD.IRDropReport: null
    #KLayout.XOR: null
    #Netgen.LVS: null
    #Checker.LVS: null
    
    # Disable chip finishing
    KLayout.Antenna: null
    Checker.KLayoutAntenna: null
    KLayout.SealRing: null
    KLayout.Filler: null
    KLayout.Density: null
    Checker.KLayoutDensity: null
    
    # Because of hierarchy
    Checker.YosysUnmappedCells: null

DESIGN_NAME: chip_top
VERILOG_FILES:
- dir::../src/chip_top.sv
- dir::../src/chip_core.sv
- dir::../src/synchronizer.sv
- dir::../ip/fabric_config/fabric_config.sv
- dir::../ip/fabric_spi/fabric_spi_controller.sv
- dir::../ip/fabric_spi/fabric_spi_receiver.sv

# Enable plugin for better SystemVerilog support
# USE_SLANG: True

SYNTH_HIERARCHY_MODE: keep

# Slightly smaller file sizes
PRIMARY_GDSII_STREAMOUT_TOOL: klayout

LINTER_DISABLE_WARNINGS:
- DECLFILENAME
- EOFNEWLINE
- PINCONNECTEMPTY
- PINMISSING
- UNUSEDSIGNAL

PAD_CFG: dir::pad_cfg.tcl

# Specify the pad instances for the padring
PAD_SOUTH: [
    # 11 pads
    "vddio_pads\\[0\\].vddio_pad",
    "vssio_pads\\[0\\].vssio_pad",

    "bidirs\\[6\\].bidir_pad",
    "bidirs\\[7\\].bidir_pad",
    "bidirs\\[8\\].bidir_pad",
    "bidirs\\[9\\].bidir_pad",
    "bidirs\\[10\\].bidir_pad",
    "bidirs\\[11\\].bidir_pad",
    "bidirs\\[12\\].bidir_pad",

    "vddio_pads\\[1\\].vddio_pad",
    "vssio_pads\\[1\\].vssio_pad"
]

PAD_EAST: [
    # 20 pads
    "vccd_pads\\[0\\].vccd_pad",
    "vssd_pads\\[0\\].vssd_pad",

    "bidirs\\[13\\].bidir_pad",
    "bidirs\\[14\\].bidir_pad",
    "bidirs\\[15\\].bidir_pad",
    "bidirs\\[16\\].bidir_pad",
    "bidirs\\[17\\].bidir_pad",
    "bidirs\\[18\\].bidir_pad",
    "bidirs\\[19\\].bidir_pad",
    "bidirs\\[20\\].bidir_pad",
    "bidirs\\[21\\].bidir_pad",
    "bidirs\\[22\\].bidir_pad",
    "bidirs\\[23\\].bidir_pad",
    "bidirs\\[24\\].bidir_pad",
    "bidirs\\[25\\].bidir_pad",
    "bidirs\\[26\\].bidir_pad",
    "bidirs\\[27\\].bidir_pad",
    "bidirs\\[28\\].bidir_pad",
    
    "vccd_pads\\[1\\].vccd_pad",
    "vssd_pads\\[1\\].vssd_pad"
]

PAD_NORTH: [
    # 11 pads
    "vddio_pads\\[3\\].vddio_pad",
    "vssio_pads\\[3\\].vssio_pad",

    "bidirs\\[35\\].bidir_pad",
    "bidirs\\[34\\].bidir_pad",
    "bidirs\\[33\\].bidir_pad",
    "bidirs\\[32\\].bidir_pad",
    "bidirs\\[31\\].bidir_pad",
    "bidirs\\[30\\].bidir_pad",
    "bidirs\\[29\\].bidir_pad",

    "vddio_pads\\[2\\].vddio_pad",
    "vssio_pads\\[2\\].vssio_pad"
]

PAD_WEST: [
    # 21 pads
    "vccd_pads\\[3\\].vccd_pad",
    "vssd_pads\\[3\\].vssd_pad",

    "bidirs\\[5\\].bidir_pad",
    "bidirs\\[4\\].bidir_pad",
    "bidirs\\[3\\].bidir_pad",

    "bidirs\\[2\\].bidir_pad",
    "bidirs\\[1\\].bidir_pad",
    "bidirs\\[0\\].bidir_pad",

    spi_mode_pad,

    spi_sclk_pad,
    spi_cs_n_pad,
    spi_mosi_pad,
    spi_miso_pad,
    
    clock_pad,
    reset_pad,
    
    "fpga_selects\\[1\\].fpga_select_pad",
    "fpga_selects\\[0\\].fpga_select_pad",
  
    config_busy_pad,

    global_enable_pad,
        
    "vccd_pads\\[2\\].vccd_pad",
    "vssd_pads\\[2\\].vssd_pad"
]

# SDC files
PNR_SDC_FILE: dir::chip_top.sdc
SIGNOFF_SDC_FILE: dir::chip_top.sdc
FALLBACK_SDC: dir::chip_top.sdc

# Power / ground nets
VDD_NETS:
- VCCD
GND_NETS:
- VSSD

# Clock
CLOCK_PORT: clk_PAD
CLOCK_NET: clock_pad/IN

# The clock is low freq because of
# the complicated clock tree.
# The frequency can be increased after
# configuring the FPGA fabrics.
CLOCK_PERIOD: 50 # 20 MHz clock

CTS_OBSTRUCTION_AWARE: True
CTS_CLK_MAX_WIRE_LENGTH: 1000

# Floorplanning
FP_SIZING: absolute

# Die area without sealring
DIE_AREA: [0, 0, "expr::(3600 - 12)", "expr::(5200 - 12)"]
CORE_AREA: [250, 250, "expr::$DIE_AREA[2] - 250", "expr::$DIE_AREA[3] - 250"]

# Prevent routing close to the padring
ROUTING_OBSTRUCTIONS:
# Left
- [met1, 0, 0, 199.7, "expr::$DIE_AREA[3]"]
- [met2, 0, 0, 199.7, "expr::$DIE_AREA[3]"]
- [met3, 0, 0, 199.7, "expr::$DIE_AREA[3]"]
- [met4, 0, 0, 199.7, "expr::$DIE_AREA[3]"]
- [met5, 0, 0, 199.7, "expr::$DIE_AREA[3]"]
# Right
- [met1, "expr::$DIE_AREA[2] - 199.7", 0, "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
- [met2, "expr::$DIE_AREA[2] - 199.7", 0, "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
- [met3, "expr::$DIE_AREA[2] - 199.7", 0, "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
- [met4, "expr::$DIE_AREA[2] - 199.7", 0, "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
- [met5, "expr::$DIE_AREA[2] - 199.7", 0, "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
# Bottom
- [met1, 0, 0, "expr::$DIE_AREA[2]", 199.7]
- [met2, 0, 0, "expr::$DIE_AREA[2]", 199.7]
- [met3, 0, 0, "expr::$DIE_AREA[2]", 199.7]
- [met4, 0, 0, "expr::$DIE_AREA[2]", 199.7]
- [met5, 0, 0, "expr::$DIE_AREA[2]", 199.7]
# Top
- [met1, 0, "expr::$DIE_AREA[3] - 199.7", "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
- [met2, 0, "expr::$DIE_AREA[3] - 199.7", "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
- [met3, 0, "expr::$DIE_AREA[3] - 199.7", "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
- [met4, 0, "expr::$DIE_AREA[3] - 199.7", "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]
- [met5, 0, "expr::$DIE_AREA[3] - 199.7", "expr::$DIE_AREA[2]", "expr::$DIE_AREA[3]"]

# Increase for more logic
# on your die
PL_TARGET_DENSITY_PCT: 34
GRT_ALLOW_CONGESTION: true

# PDN
PDN_HWIDTH: 3.2
PDN_HPITCH: 100

PDN_VWIDTH: 1.6
PDN_VPITCH: 80

PDN_CORE_RING: True

# Maximum metal width without slotting: 30um
PDN_CORE_RING_VWIDTH: 15
PDN_CORE_RING_HWIDTH: 15
# Ensure minimum spacing for long metals
PDN_CORE_RING_VSPACING: 5
PDN_CORE_RING_HSPACING: 5

PDN_CORE_VERTICAL_LAYER: met2
PDN_CORE_HORIZONTAL_LAYER: met3

PDN_CORE_RING_CONNECT_TO_PADS: True
PDN_CORE_RING_CONNECT_TO_PAD_LAYERS: [met3]
PDN_ENABLE_PINS: False # xxx does not contain any terminals
ERROR_ON_PDN_VIOLATIONS: False # to prevent false positive error

IGNORE_DISCONNECTED_MODULES:
- sky130_fd_io__top_power_hvc_wpad
- sky130_fd_io__top_ground_hvc_wpad
- sky130_fd_io__top_power_lvc_wpad
- sky130_fd_io__top_ground_lvc_wpad
- caravel_logo
- caravel_motto
- open_source
- project_id_textblock
- logo_fabulous

MACROS:
  classic_fabric_chipfoundry_small:
    gds:
      - dir::../fabrics/classic_fabric_chipfoundry_small/macro/sky130A/gds/classic_fabric_chipfoundry_small.gds
    lef:
      - dir::../fabrics/classic_fabric_chipfoundry_small/macro/sky130A/lef/classic_fabric_chipfoundry_small.lef
    nl:
      - dir::../fabrics/classic_fabric_chipfoundry_small/macro/sky130A/nl/classic_fabric_chipfoundry_small.nl.v
    instances:
    # x should be multiple of 0.46 (Metal2 pitch)
    # y should be multiple of 0.68 (Metal3 pitch)
    # Standard cell row height: 2.72 (4 Metal3 tracks)
      i_chip_core/i_classic_fabric_chipfoundry_small:
        location: ["expr::(349.6 + (0.46 * 45))", expr::(3289.84 + (2.72 * 18))]
        orientation: N

  classic_fabric_chipfoundry_medium:
    gds:
      - dir::../fabrics/classic_fabric_chipfoundry_medium/macro/sky130A/gds/classic_fabric_chipfoundry_medium.gds
    lef:
      - dir::../fabrics/classic_fabric_chipfoundry_medium/macro/sky130A/lef/classic_fabric_chipfoundry_medium.lef
    nl:
      - dir::../fabrics/classic_fabric_chipfoundry_medium/macro/sky130A/nl/classic_fabric_chipfoundry_medium.nl.v
    instances:
      i_chip_core/i_classic_fabric_chipfoundry_medium:
        location: ["expr::(1389.66 + (0.46 * 100))", expr::(3289.84 + (2.72 * 18))]
        orientation: N

  classic_fabric_chipfoundry_large:
    gds:
      - dir::../fabrics/classic_fabric_chipfoundry_large/macro/sky130A/gds/classic_fabric_chipfoundry_large.gds
    lef:
      - dir::../fabrics/classic_fabric_chipfoundry_large/macro/sky130A/lef/classic_fabric_chipfoundry_large.lef
    nl:
      - dir::../fabrics/classic_fabric_chipfoundry_large/macro/sky130A/nl/classic_fabric_chipfoundry_large.nl.v
    instances:
      i_chip_core/i_classic_fabric_chipfoundry_large:
        location: ["expr::(349.6 + (0.46 * 45))", expr::(110 * 2.72)]
        orientation: FS

  caravel_logo:
    gds:
      - dir::../ip/caravel_logo/gds/caravel_logo.gds.gz
    lef:
      - dir::../ip/caravel_logo/lef/caravel_logo.lef
    vh:
      - dir::../ip/caravel_logo/vh/caravel_logo.vh
    instances:
      caravel_logo:
        location: [27.800, 5039.200]
        orientation: N

  caravel_motto:
    gds:
      - dir::../ip/caravel_motto/gds/caravel_motto.gds.gz
    lef:
      - dir::../ip/caravel_motto/lef/caravel_motto.lef
    vh:
      - dir::../ip/caravel_motto/vh/caravel_motto.vh
    instances:
      caravel_motto:
        location: [109.850, 5086.950]
        orientation: N

  open_source:
    gds:
      - dir::../ip/open_source/gds/open_source.gds.gz
    lef:
      - dir::../ip/open_source/lef/open_source.lef
    vh:
      - dir::../ip/open_source/vh/open_source.vh
    instances:
      open_source:
        location: [3381.410, 5091.710]
        orientation: N

  project_id_textblock:
    gds:
      - dir::../ip/project_id_textblock/gds/project_id_textblock.gds.gz
    lef:
      - dir::../ip/project_id_textblock/lef/project_id_textblock.lef
    vh:
      - dir::../ip/project_id_textblock/vh/project_id_textblock.vh
    instances:
      project_id_textblock:
        location: [58.250, 59.02]
        orientation: N

  logo_fabulous:
    gds:
      - dir::../ip/logo_fabulous/gds/logo_fabulous.gds.gz
    lef:
      - dir::../ip/logo_fabulous/lef/logo_fabulous.lef
    vh:
      - dir::../ip/logo_fabulous/vh/logo_fabulous.vh
    instances:
      logo_fabulous:
        location: [3450, 50]
        orientation: N

PDN_MACRO_CONNECTIONS:
- "i_chip_core/i_classic_fabric_chipfoundry_large VPWR VGND VCCD VSSD"
- "i_chip_core/i_classic_fabric_chipfoundry_small VPWR VGND VCCD VSSD"
- "i_chip_core/i_classic_fabric_chipfoundry_medium VPWR VGND VCCD VSSD"

# Because we have multiple power pads for one power domain
MAGIC_EXT_UNIQUE: notopports

# Render the image
KLAYOUT_RENDER_RESOLUTION: 1024
KLAYOUT_RENDER_OVERSAMPLING: 3
KLAYOUT_PROPERTIES: dir::sky130_render.lyp

PL_RESIZER_HOLD_SLACK_MARGIN: expr::(0.1 * 2)
GRT_RESIZER_HOLD_SLACK_MARGIN: expr::(0.05 * 2)

# We're not interested in 1v95
HOLD_VIOLATION_CORNERS:
- nom_tt_025C_1v80
- nom_ss_100C_1v60
#- nom_ff_n40C_1v95
- min_tt_025C_1v80
- min_ss_100C_1v60
#- min_ff_n40C_1v95
- max_tt_025C_1v80
- max_ss_100C_1v60
#- max_ff_n40C_1v95

#EXTRA_GDS:
#- pdk_dir::libs.ref/sky130_fd_io/gds/sky130_ef_io__analog.gds

EXTRA_LIBS:
- dir::sky130_ef_io__analog_esd_pad.lib

#PAD_PLACE_IO_TERMINALS:
#- sky130_ef_io__gpiov2_pad/PAD
#- sky130_ef_io__vccd_lvc_clamped_pad/VCCD_PAD
#- sky130_ef_io__vssd_lvc_clamped_pad/VSSD_PAD
#- sky130_ef_io__vddio_hvc_clamped_pad/VDDIO_PAD
#- sky130_ef_io__vssio_hvc_clamped_pad/VSSIO_PAD
#- sky130_ef_io__analog_esd_pad/P_PAD

RSZ_DONT_TOUCH_LIST: 
- global_enable_PAD2CORE
